/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElTreeNode: typeof import('element-plus/es')['ElTreeNode']
}
